# Generated by Django 5.2.5 on 2025-08-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0003_sensor_uuid_alter_sensor_id_alter_sensor_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
    ]
