# Generated by Django 5.2.5 on 2025-08-11 20:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_api', '0004_remove_sensor_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsegment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='lat_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='lat_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='length',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='long_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='long_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='speed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
